### PR TITLE
Use native React context API

### PR DESCRIPTION
**Pull request by smashercosmo**
Reasoning behind PR:
  1. Smaller package
  2. Fewer dependencies
  3. Utilizing native context implementation, which is better integrated in React rendering flow
  4. Famous react packages like react-router, emotion, styled-components, react-final-form are already 
      in the process of migrating to React context.

This is a breaking changes, so it'll require v3.0 release.

### CODE REVIEW

**Comment by TrySound** [comment]
The third point is not the problem
https://github.com/jamiebuilds/create-react-context/blob/master/src/index.js#L5

**Comment by smashercosmo** [comment]
@TrySound Yeah, if this PR https://github.com/jamiebuilds/unstated/pull/46 is merged it won't be :)

**Comment by smashercosmo** [comment]
For Travis not to fail, I probably need to include updated yarn.lock file to this PR, right?

**Comment by TrySound** [comment]
Yes

**Comment by smashercosmo** [comment]
Ok, I had to update flow to make build pass

**Comment by smashercosmo** [comment]
Am I right, that this won't be merged in any near future?

**Comment by JeroenReumkens** [comment]
Great change! I think this is also a necessary change if we want to support the new StrictMode. I hope @jamiebuilds will soon take a look at your pull request.

**Pull request closed without merging**
